project_id = "qpxzuglvvfvookzmpgfe"

[functions.send-sms]
verify_jwt = false

[functions.send-notification-sms]
verify_jwt = false

[functions.webhook-orders]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.process-auto-followups]
verify_jwt = false

[functions.auto-distribute-orders]
verify_jwt = false

[functions.sync-order-elementor]
verify_jwt = true
